parameters:

services:
    vep_reservation.theater:
        class: Vep\ReservationBundle\Service\Theater
    
    vep_reservation.form.type.reservation:
        class: Vep\ReservationBundle\Form\Type\ReservationType
        arguments: [@vep_reservation.theater]
        tags:
            - { name: form.type, alias: form_reservation }
    
    vep_reservation.form.type.production:
        class: Vep\ReservationBundle\Form\Type\ProductionType
        tags:
            - { name: form.type, alias: form_production }
    
    vep_reservation.form.type.session:
        class: Vep\ReservationBundle\Form\Type\SessionType
        tags:
            - { name: form.type, alias: form_session }