parameters:
#    vep_reservation.example.class: Vep\ReservationBundle\Example

services:
#    vep_reservation.example:
#        class: %vep_reservation.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
