parameters:

services:
    vep_reservation.theater:
        class: Vep\ReservationBundle\Service\Theater
    
    vep_reservation.form.type.reservation:
        class: Vep\ReservationBundle\Form\Type\ReservationType
        arguments: [@vep_reservation.theater]
        tags:
            - { name: form.type, alias: form_reservation }