<?php

namespace Vep\ReservationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProductionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductionRepository extends EntityRepository
{
    public function findComing() {
        return $this->createQueryBuilder('p')
                    ->join('p.sessions', 's')
                    ->where('s.date > :date')
                    ->orderBy('s.date', 'asc')
                    ->setFirstResult(0)
                    ->setMaxResults(1)
                    ->setParameter('date', new \Datetime())
                    ->getQuery()
                    ->getOneOrNullResult();
    }
}
